export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_USER_LOGOUT: "SET_CURRENT_USER_LOGOUT",
  SET_CURRENT_USER_LOADING: "SET_CURRENT_USER_LOADING",
  SET_CURRENT_USER_ERROR: "SET_CURRENT_USER_ERROR",
  SET_CURRENT_USER_SELECTED_PROJECTID: "SET_CURRENT_USER_SELECTED_PROJECTID",
};
