const Mymovies = [
  { id: 1, name: "Men in Black" },
  { id: 2, name: "Terminator" },
  { id: 3, name: "Godzilla" },
  { id: 4, name: "Superman" },
  { id: 5, name: "Hot fuzz" },
  { id: 6, name: "Men in Black" },
  { id: 7, name: "Terminator" },
  { id: 8, name: "Godzilla" },
  { id: 9, name: "Superman" },
  { id: 10, name: "Hot fuzz" },
  { id: 11, name: "Men in Black" },
  { id: 12, name: "Terminator" },
  { id: 13, name: "Godzilla" },
  { id: 14, name: "Superman" },
  { id: 15, name: "Hot fuzz" },
  { id: 16, name: "Men in Black" },
  { id: 17, name: "Terminator" },
  { id: 18, name: "Godzilla" },
  { id: 19, name: "Godzilla" },
  { id: 20, name: "Superman" },
  { id: 21, name: "Men in Black" },
  { id: 22, name: "Terminator" },
  { id: 23, name: "Godzilla" },
  { id: 24, name: "Superman" },
  { id: 25, name: "Hot fuzz" },
  { id: 26, name: "Men in Black" },
  { id: 27, name: "Terminator" },
  { id: 28, name: "Godzilla" },
  { id: 29, name: "Superman" },
  { id: 30, name: "Superman" },
  { id: 31, name: "Men in Black" },
  { id: 32, name: "Terminator" },
  { id: 33, name: "Godzilla" },
  { id: 34, name: "Superman" },
  { id: 35, name: "Hot fuzz" },
  { id: 36, name: "Men in Black" },
  { id: 37, name: "Terminator" },
  { id: 38, name: "Godzilla" },
  { id: 39, name: "Superman" },
  { id: 40, name: "Superman" },
  { id: 41, name: "Men in Black" },
  { id: 42, name: "Terminator" },
  { id: 43, name: "Godzilla" },
  { id: 44, name: "Superman" },
  { id: 45, name: "Hot fuzz" },
  { id: 46, name: "Men in Black" },
  { id: 47, name: "Terminator" },
  { id: 48, name: "Godzilla" },
  { id: 49, name: "Superman" },
  { id: 50, name: "Superman" },
  { id: 51, name: "Men in Black" },
  { id: 52, name: "Terminator" },
  { id: 53, name: "Godzilla" },
  { id: 54, name: "Superman" },
  { id: 55, name: "Hot fuzz" },
  { id: 56, name: "Men in Black" },
  { id: 57, name: "Terminator" },
  { id: 58, name: "Godzilla" },
  { id: 59, name: "Superman" },
  { id: 60, name: "Superman" },
  { id: 61, name: "Men in Black" },
  { id: 62, name: "Terminator" },
  { id: 63, name: "Godzilla" },
  { id: 64, name: "Superman" },
  { id: 65, name: "Hot fuzz" },
  { id: 66, name: "Men in Black" },
  { id: 67, name: "Terminator" },
  { id: 68, name: "Godzilla" },
  { id: 69, name: "Superman" },
  { id: 70, name: "Superman" },
  { id: 71, name: "Men in Black" },
  { id: 72, name: "Terminator" },
  { id: 73, name: "Godzilla" },
  { id: 74, name: "Superman" },
  { id: 75, name: "Hot fuzz" },
  { id: 76, name: "Men in Black" },
  { id: 77, name: "Terminator" },
  { id: 78, name: "Godzilla" },
  { id: 79, name: "Superman" },
  { id: 80, name: "Superman" },
  { id: 81, name: "Men in Black" },
  { id: 82, name: "Terminator" },
  { id: 83, name: "Godzilla" },
  { id: 84, name: "Superman" },
  { id: 85, name: "Hot fuzz" },
  { id: 86, name: "Men in Black" },
  { id: 87, name: "Terminator" },
  { id: 88, name: "Godzilla" },
  { id: 89, name: "Superman" },
  { id: 90, name: "Superman" },
  { id: 91, name: "Men in Black" },
  { id: 92, name: "Terminator" },
  { id: 93, name: "Godzilla" },
  { id: 94, name: "Superman" },
  { id: 95, name: "Hot fuzz" },
  { id: 96, name: "Men in Black" },
  { id: 97, name: "Terminator" },
  { id: 98, name: "Godzilla" },
  { id: 99, name: "Superman" },
  { id: 100, name: "Superman" },
];

export default Mymovies;
